version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tms-postgres
    environment:
      POSTGRES_DB: "TaskManagementDB"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YourStrong@Passw0rd"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d TaskManagementDB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build:
      context: ./backend/TMS.API
      dockerfile: Dockerfile
    container_name: tms-api
    ports:
      - "5299:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=TaskManagementDB;Username=postgres;Password=YourStrong@Passw0rd"
      Jwt__Key: "YourSuperSecretKeyThatIsAtLeast32CharactersLong!"
      Jwt__Issuer: "TMS.API"
      Jwt__Audience: "TMS.Angular"
      Jwt__ExpiryMinutes: "60"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./UI/myapp
      dockerfile: Dockerfile
    container_name: tms-frontend
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  postgres_data:
